### ISSUE TITLE
GraphQL support with nosql database

### ISSUE THREAD

**Issue by MohitTilwani15** [vuesion/packages#16]
@devCrossNet  What do you think about adding a feature that when user runs `npx @vuesion/service create my-app` we can ask some questions while installation like do you want GraphQL and after that some options of nosql database support?

**Comment by devCrossNet** [comment]
I like the idea, but because it's a really opinionated boilerplate I would rather provide an add-on that can be installed via `vuesion add`

**Comment by devCrossNet** [comment]
GraphQL support for the next vuesion version is provided by https://github.com/nuxt-community/apollo-module
